version: '3.8'

services:
############################
# Setup database container #
############################
  postgres_db:
    image: postgres:12.2
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4:5.1
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: always
    ports:
      - ${PGADMIN_PORT}:8080/tcp
    environment: 
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}


  dbMysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}

  adminer:
    image: dockette/adminer
    container_name: ${ADMINER_CONTAINER_NAME}
    restart: always
    ports:
      - ${ADMINER_PORT}:80
