version: '3'

services:
    adminer:
        image: dockette/adminer:full-php5
        restart: always
        ports:
            - ${ADMINER_PORT}:80

    dbPostgres:
        image: postgres:10
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
