version: '3'

services:
    adminer:
        # image: dockette/adminer:full-php5
        image: dockette/adminer
        restart: always
        container_name: ${ADMINER_CONTAINER_NAME}
        ports:
            - ${ADMINER_PORT}:80

    dbPostgres:
        image: postgres:10
        container_name: ${POSTGRES_CONTAINER_NAME}
        restart: always
        volumes:
            - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    dbMysql:
        image: mysql:8.0.15
        command: --default-authentication-plugin=mysql_native_password
        container_name: ${MYSQL_CONTAINER_NAME}
        restart: always
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB}
